### ISSUE TITLE
Client stops syncing after a while because of losing p2p connections 

### ISSUE THREAD

**Issue by steffenkux** [PegaSysEng/pantheon#228] opened 2018-11-01 10:06 UTC
### Description
Syncing the clinet from scratch.

### Acceptance Criteria
* get syncronized 

### Steps to Reproduce (Bug)
1. install
2. start client (on windows10)
3. wait a while

**Expected behavior:** [What you expect to happen]
* keeps syncing
* has contact to other nodes

**Actual behavior:** [What actually happens]
* stops syncing
* loses connection to other clients (?)

**Frequency:** [What percentage of the time does it occur?]
* always, somtimes it syncs a little bit, somtimes not

### Versions (Add all that apply)
* Software version: 0.8.1
* Java version: 8u191
* OS Name & Version: win10 pro 
* Kernel Version: 1803

### Additional Information
see errorlog (appended)
[errorlog_pantheon.txt](https://github.com/PegaSysEng/pantheon/files/2538034/errorlog_pantheon.txt)

**Comment by steffenkux** [comment] 2018-11-01 10:07
[errorlog_pantheon.txt](https://github.com/PegaSysEng/pantheon/files/2538038/errorlog_pantheon.txt)

**Comment by lucassaldanha** [comment] 2018-11-01 10:16
Hi @steffenkux ,

Could you try running it using the `--p2p-listen` property to advertise your public IP properly?
You just need to add the property on the startup command `--p2p-listen=host:30303`, replacing `host` with your public IP.

Also, ensure that TCP and UDP traffic is allowed on port 30303 in you firewall settings.

Let me know if this solves the issue.

**Comment by 5chdn** [comment] 2018-11-01 11:45
Having the same issue: https://gist.github.com/5chdn/1939f043078905580a80ffd686c6c375

```
2018-11-01 12:38:09.984+01:00 | nioEventLoopGroup-3-1 | ERROR | Downloader | Encountered error importing blocks
tech.pegasys.pantheon.ethereum.eth.manager.exceptions.MaxRetriesReachedException: Task failed: MAX_RETRIES_REACHED
	at tech.pegasys.pantheon.ethereum.eth.manager.AbstractRetryingPeerTask.executeTask(AbstractRetryingPeerTask.java:45) [pantheon-eth-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.ethereum.eth.manager.AbstractRetryingPeerTask.lambda$handleTaskError$1(AbstractRetryingPeerTask.java:82) [pantheon-eth-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) [?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) [?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) [?:?]
	at tech.pegasys.pantheon.ethereum.eth.sync.tasks.WaitForPeerTask.lambda$executeTask$0(WaitForPeerTask.java:50) [pantheon-eth-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.ethereum.eth.manager.EthPeers.lambda$invokeConnectionCallbacks$5(EthPeers.java:127) [pantheon-eth-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4791) [?:?]
	at tech.pegasys.pantheon.util.Subscribers.forEach(Subscribers.java:78) [pantheon-util-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.ethereum.eth.manager.EthPeers.invokeConnectionCallbacks(EthPeers.java:127) [pantheon-eth-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.ethereum.eth.manager.EthPeer.maybeExecuteStatusesExchangedCallback(EthPeer.java:255) [pantheon-eth-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.ethereum.eth.manager.EthPeer.registerStatusReceived(EthPeer.java:246) [pantheon-eth-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.ethereum.eth.manager.EthProtocolManager.handleStatusMessage(EthProtocolManager.java:240) [pantheon-eth-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.ethereum.eth.manager.EthProtocolManager.processMessage(EthProtocolManager.java:156) [pantheon-eth-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.ethereum.p2p.NetworkRunner.lambda$setupHandlers$0(NetworkRunner.java:132) [pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.ethereum.p2p.netty.Callbacks.lambda$invokeSubProtocol$1(Callbacks.java:61) [pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4791) [?:?]
	at tech.pegasys.pantheon.util.Subscribers.forEach(Subscribers.java:78) [pantheon-util-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.ethereum.p2p.netty.Callbacks.invokeSubProtocol(Callbacks.java:58) [pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.ethereum.p2p.netty.ApiHandler.channelRead0(ApiHandler.java:101) [pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at tech.pegasys.pantheon.ethereum.p2p.netty.ApiHandler.channelRead0(ApiHandler.java:31) [pantheon-p2p-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [netty-codec-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) [netty-codec-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-codec-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-common-4.1.15.Final.jar:4.1.15.Final]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

**Comment by 5chdn** [comment] 2018-11-01 11:46
Same as #222

**Comment by 5chdn** [comment] 2018-11-01 11:54
`❯ bin/pantheon --rpc-enabled --p2p-listen=80.187.100.147:30303`

does cause the same

**Comment by lucassaldanha** [comment] 2018-11-01 12:53
Hi guys, I've been trying to reproduce this issue but so far my node hasn't had any issues with the sync. Could you please confirm the version/commit that you are using?

If you aren't on the latest master version, could you please try with our latest commit?

Cheers!

**Comment by 5chdn** [comment] 2018-11-01 14:45
```
❯ git log -n1
commit c53dd6e3b35c8f22b22f855f8629f000d03b56e6 (HEAD -> master)
```

did you try to run it on a local machine, i.e., a laptop that has different networking restrictions than a cloud server?

**Comment by steffenkux** [comment] 2018-11-01 14:54
I used the latest available package (0.8.1).


-- 
___________________________________________________________________________


*slock.it <http://slock.it/> GmbH, Markt 16, 09648 Mittweida, Germany*


Sitz/Registered Office: *Mittweida* | Registergericht/Registration Court: 
*Amtsgericht Chemnitz*
Registernummer/Company Registration Number: *HRB 
30026* | Ust-ID/VAT ID: *DE303959655*
Geschäftsführer/CEO: *Christoph 
Jentzsch*


___________________________________________________________________________


The information contained in this message may be confidential and is 
intended to be

exclusively for the addressee. Should you receive this 
message unintentionally, please

do not use these contents and notify the 
sender immediately by return e-mail.

**Comment by shemnon** [comment] 2018-11-01 14:56
It's broke in 0.8.1.  It's fixed in master and the 0.8.x branch.  For the next few days you will need to build from source.

**Comment by lucassaldanha** [comment] 2018-11-01 15:05
> did you try to run it on a local machine, i.e., a laptop that has different networking restrictions than a cloud server?

I'll give it a shot. Thanks for the update.

**Comment by shemnon** [comment] 2018-11-01 15:17
@5chdn has the quick fix, so it looks like the fix only partly works.

**Comment by 5chdn** [comment] 2018-11-02 09:15
There is only a change to the Dockerfile on master, don't think this is the fix?

**Comment by lucassaldanha** [comment] 2018-11-02 09:31
> There is only a change to the Dockerfile on master, don't think this is the fix?

I think what @shemnon meant is that the fix that was supposed to mitigate this (6ccb06012ee8b9ee2a75f83f42dc982b682e4fde) doesn't seem to work. We are investigating this and we'll update this ticket as soon as we have more details.

**Comment by ajsutton** [comment] 2018-11-03 11:01
We've merged in https://github.com/PegaSysEng/pantheon/pull/231 which is a more comprehensive solution to the MAX_RETRIES errors we've been seeing.  It would be great if people could test out the latest master and let us know if it's helped this case.

**Comment by ajsutton** [comment] 2018-11-13 21:16
As far as we can tell this issue has been fixed.  Please yell if you're still experiencing it.

**Closed by ajsutton** 2018-11-13 21:16 UTC
Labels: bug

**Comment by carlosfaria94** [comment] 2019-01-02 13:41
@ajsutton I'm experiencing the same issue with the last version (0.8.3)

```
$ git log -n1
commit 4ef2082408993859f47e413c584008e035821e88 (HEAD -> master, origin/master, origin/HEAD)
Author: Rob Dawson <robert@rojotek.com>
Date:   Mon Dec 31 11:24:15 2018 +1000

    Added in support for the JSON RPC Eth Hashrate method. (#488)
```

Start: `$ pantheon --rpc-enabled --datadir=custom-dir --p2p-listen=myip:30303`

Error:

```
2019-01-02 13:35:03.434+00:00 | EthSchedulerTimer | WARN  | PipelinedImportChainSegmentTask | Import of chain segment (15680 to 15860) failed: Task failed: MAX_RETRIES_REACHED.
2019-01-02 13:35:05.439+00:00 | EthSchedulerTimer | INFO  | AbstractRetryingPeerTask | No peers available, wait for peer.
2019-01-02 13:35:10.441+00:00 | EthSchedulerTimer | INFO  | AbstractRetryingPeerTask | No peers available, wait for peer.
2019-01-02 13:35:15.443+00:00 | EthSchedulerTimer | INFO  | AbstractRetryingPeerTask | No peers available, wait for peer.
2019-01-02 13:35:20.444+00:00 | EthSchedulerTimer | INFO  | AbstractRetryingPeerTask | No peers available, wait for peer.
^C2019-01-02 13:35:23.999+00:00 | Thread-2 | INFO  | NetworkRunner | Stopping Network.
2019-01-02 13:35:24.005+00:00 | Thread-2 | INFO  | EthProtocolManager | Stopping eth Subprotocol.
2019-01-02 13:35:25.448+00:00 | EthSchedulerTimer | WARN  | PipelinedImportChainSegmentTask | Import of chain segment (15680 to 15860) failed: Task failed: MAX_RETRIES_REACHED.
2019-01-02 13:35:25.448+00:00 | EthSchedulerTimer | ERROR | Downloader | Encountered error importing blocks
tech.pegasys.pantheon.ethereum.eth.manager.exceptions.MaxRetriesReachedException: Task failed: MAX_RETRIES_REACHED
	at tech.pegasys.pantheon.ethereum.eth.manager.AbstractRetryingPeerTask.executeTask(AbstractRetryingPeerTask.java:66) ~[pantheon-eth-0.8.3.jar:0.8.3]
	at tech.pegasys.pantheon.ethereum.eth.manager.AbstractEthTask.executeTaskTimed(AbstractEthTask.java:134) ~[pantheon-eth-0.8.3.jar:0.8.3]
	at tech.pegasys.pantheon.ethereum.eth.manager.AbstractRetryingPeerTask.lambda$handleTaskError$1(AbstractRetryingPeerTask.java:105) ~[pantheon-eth-0.8.3.jar:0.8.3]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[?:1.8.0_131]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[?:1.8.0_131]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_131]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_131]
	at tech.pegasys.pantheon.ethereum.eth.manager.EthScheduler.lambda$failAfterTimeout$9(EthScheduler.java:236) ~[pantheon-eth-0.8.3.jar:0.8.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
2019-01-02 13:35:25.450+00:00 | EthSchedulerTimer | ERROR | Downloader | Error encountered while downloading
java.util.concurrent.CompletionException: tech.pegasys.pantheon.ethereum.eth.manager.exceptions.MaxRetriesReachedException: Task failed: MAX_RETRIES_REACHED
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_131]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_131]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593) ~[?:1.8.0_131]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_131]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_131]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_131]
	at tech.pegasys.pantheon.ethereum.eth.manager.AbstractRetryingPeerTask.executeTask(AbstractRetryingPeerTask.java:66) ~[pantheon-eth-0.8.3.jar:0.8.3]
	at tech.pegasys.pantheon.ethereum.eth.manager.AbstractEthTask.executeTaskTimed(AbstractEthTask.java:134) ~[pantheon-eth-0.8.3.jar:0.8.3]
	at tech.pegasys.pantheon.ethereum.eth.manager.AbstractRetryingPeerTask.lambda$handleTaskError$1(AbstractRetryingPeerTask.java:105) ~[pantheon-eth-0.8.3.jar:0.8.3]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[?:1.8.0_131]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[?:1.8.0_131]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_131]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_131]
	at tech.pegasys.pantheon.ethereum.eth.manager.EthScheduler.lambda$failAfterTimeout$9(EthScheduler.java:236) ~[pantheon-eth-0.8.3.jar:0.8.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: tech.pegasys.pantheon.ethereum.eth.manager.exceptions.MaxRetriesReachedException: Task failed: MAX_RETRIES_REACHED
	... 14 more
```
