### ISSUE TITLE
Sync with Rinkeby doesn't work in Windows 10 / macos

### ISSUE THREAD

**Issue by ice09** [PegaSysEng/pantheon#222] opened 2018-10-31 23:27 UTC
### Description
Starting Rinkeby (pantheon.bat --rinkeby) shows 
java.util.concurrent.CompletionException: tech.pegasys.pantheon.ethereum.eth.manager.exceptions.MaxRetriesReachedException: Task failed: MAX_RETRIES_REACHED
after some time ( Import of chain segment (270980 to 271200) failed: Task failed: MAX_RETRIES_REACHED.)
And is followed by
2018-10-31 23:43:06.516+01:00 | EthSchedulerTimer | INFO  | WaitForPeersTask | Waiting for 1 peers to connect.
2018-11-01 00:22:27.397+01:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryController | Peer table refresh triggered by timer expiry
2018-11-01 00:22:57.402+01:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryController | Peer table refresh triggered by insufficient peers
2018-11-01 00:23:27.398+01:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryController | Peer table refresh triggered by insufficient peers
2018-11-01 00:23:57.404+01:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryController | Peer table refresh triggered by insufficient peers
2018-11-01 00:24:27.398+01:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryController | Peer table refresh triggered by insufficient peers
2018-11-01 00:24:57.397+01:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryController | Peer table refresh triggered by insufficient peers

### Acceptance Criteria
* Rinkeby syncs after some time

### Steps to Reproduce (Bug)
Start pantheon.bat with --rinkeby

**Expected behavior:** 
see above

**Actual behavior:** 
see above

**Frequency:**
always

### Versions (Add all that apply)
* Software version: 0.8.1
* Java version: JDK 8u171
* OS Name & Version: Windows 10 / macos Mojave

**Comment by lucassaldanha** [comment] 2018-11-01 15:15
I'm closing this issue as a duplicate of #228. The problem is not specific to OS.

**Closed** 2018-11-01 15:15 UTC
